begin;

create table public.weekly_opt_outs (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id),
  week_id bigint not null references public.weeks(id),
  created_at timestamptz not null default now(),
  unique (player_id, week_id)
);

grant select, insert, update, delete on public.weekly_opt_outs to service_role;
grant select, insert, update, delete on public.weekly_opt_outs to authenticated;

alter table public.weekly_opt_outs enable row level security;

create policy "service_role_all" on public.weekly_opt_outs
  for all to service_role using (true) with check (true);
create policy "authenticated_all" on public.weekly_opt_outs
  for all to authenticated using (true) with check (true);

commit;